#!/bin/bash

if [[ $# < 2 ]]
then
        echo "$0 [instance ip or domain] [instance pem]"
        exit 1;
fi
INSTANCE=$1
INSTANCE_PEM=$2

DNS=$(sed ':begin /nameserver/ !d; s/nameserver //g; T begin;q' /etc/resolv.conf)

scp -i $INSTANCE_PEM ubuntu@$INSTANCE:static.key .
echo "remote $INSTANCE
dev tun
ifconfig 10.8.0.2 10.8.0.1
secret static.key
keepalive 10 60
ping-timer-rem
persist-tun
persist-key
redirect-gateway
" > client.conf

sudo openvpn --config client.conf &

sudo route add $DNS gw 192.168.0.254

trap "kill %1" INT
wait %1
trap INT

sudo route del $DNS gw 192.168.0.254
rm client.conf
rm static.key
